spring:
  datasource:
    url: jdbc:postgresql://188.120.235.15:5432/vtbmock
    username: flareon
    password: Byzb4QHquHjiyNN

jwt.secret: mymagicmanjwtsecretmymagicmanjwtsecretmymagicmanjwtsecretmymagicmanjwtsecretmymagicmanjwtsecretmymagicmanjwtsecretmymagicmanjwtsecretmymagicmanjwtsecret


